#!/usr/bin/env python3
"""Generates the correct vLLM launch script without any PowerShell $-variable interference."""
import os, stat

DYNAMO_BIN = "/home/nwasim/dynamo-env/bin"
CUDA_HOME  = "/home/nwasim/dynamo-env/lib/python3.12/site-packages/nvidia/cu13"
MODEL      = "/home/nwasim/models/Llama-3.1-8B-Instruct"
SCRIPT     = "/tmp/ddn_start_vllm.sh"

# Build PATH explicitly — no shell variable expansion needed
safe_path = ":".join([
    DYNAMO_BIN,
    f"{CUDA_HOME}/bin",
    "/usr/local/sbin", "/usr/local/bin", "/usr/sbin", "/usr/bin", "/sbin", "/bin"
])

content = f"""#!/bin/bash
# DDN vLLM Launch Script — generated by ddn_write_vllm_script.py
# CUDA_HOME points to nvidia Python package containing nvcc for FlashInfer JIT
export CUDA_HOME={CUDA_HOME}
export PATH={safe_path}
export VIRTUAL_ENV={DYNAMO_BIN[:-4]}
export VLLM_WORKER_MULTIPROC_METHOD=fork
exec {DYNAMO_BIN}/python3 -m vllm.entrypoints.openai.api_server \\
  --model {MODEL} \\
  --served-model-name meta-llama/Llama-3.1-8B-Instruct \\
  --enable-prefix-caching \\
  --enforce-eager \\
  --port 11000 \\
  --max-model-len 16384 \\
  --gpu-memory-utilization 0.92
"""

with open(SCRIPT, "w") as f:
    f.write(content)
os.chmod(SCRIPT, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP)
print("Written:", SCRIPT)
print("---")
print(content)
