"""
DDN KV Cache Observatory — vLLM Server Manager
Uses PM2 to manage vLLM as a named process (ddn-vllm), solving the
subprocess detachment issue when launched from uvicorn/PM2 context.
"""
import asyncio
import os
import logging
import urllib.request

logger = logging.getLogger(__name__)

# ── State ─────────────────────────────────────────────────────────────────────
_vllm_status = "stopped"   # stopped | starting | running | stopping | error
_vllm_log_lines: list[str] = []

VLLM_PORT       = 11000
VLLM_HEALTH_URL = f"http://localhost:{VLLM_PORT}/health"
MODEL_PATH      = os.path.expanduser("~/models/Llama-3.1-8B-Instruct")
LAUNCH_SCRIPT   = "/tmp/ddn_start_vllm.sh"

PM2_BIN         = "/usr/bin/pm2"
PM2_VLLM_NAME   = "ddn-vllm"

# PM2 services that hold GPU VRAM and must be paused before vLLM can load
GPU_COMPETING_SERVICES = ["infinia-rag-backend", "ddn-vss-backend"]


def _write_launch_script() -> None:
    """Write a self-contained bash script that launches vLLM with correct CUDA env.
    
    Avoids $PATH shell expansion — sets all paths explicitly so it works from
    any parent process (PM2, uvicorn, etc.) without inheriting their environment.
    """
    model    = os.path.expanduser("~/models/Llama-3.1-8B-Instruct")
    dynamo_bin = os.path.expanduser("~/dynamo-env/bin")
    dynamo_env = os.path.expanduser("~/dynamo-env")
    # nvcc lives inside the nvidia Python package installed in dynamo-env
    cuda_home = os.path.expanduser(
        "~/dynamo-env/lib/python3.12/site-packages/nvidia/cu13"
    )
    # Build a safe, minimal PATH — no shell variable expansion needed
    safe_path = ":".join([
        dynamo_bin,
        f"{cuda_home}/bin",
        "/usr/local/sbin", "/usr/local/bin",
        "/usr/sbin", "/usr/bin", "/sbin", "/bin",
    ])
    script = f"""#!/bin/bash
# DDN KV Cache Observatory — vLLM launch script (auto-generated by vllm_manager.py)
# CUDA_HOME: FlashInfer needs nvcc for JIT kernel compilation during warmup
export CUDA_HOME={cuda_home}
export PATH={safe_path}
export VIRTUAL_ENV={dynamo_env}
export VLLM_WORKER_MULTIPROC_METHOD=fork
exec {dynamo_bin}/python3 -m vllm.entrypoints.openai.api_server \\
  --model {model} \\
  --served-model-name meta-llama/Llama-3.1-8B-Instruct \\
  --enable-prefix-caching \\
  --enforce-eager \\
  --port {VLLM_PORT} \\
  --max-model-len 16384 \\
  --gpu-memory-utilization 0.92
"""
    with open(LAUNCH_SCRIPT, "w") as f:
        f.write(script)
    os.chmod(LAUNCH_SCRIPT, 0o755)
    logger.info(f"Launch script written to {LAUNCH_SCRIPT}")


async def _pm2(action: str, *args: str) -> int:
    """Run a pm2 command; return exit code."""
    cmd = [PM2_BIN, action] + list(args)
    try:
        p = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        await p.wait()
        logger.info(f"pm2 {action} {' '.join(args)} → {p.returncode}")
        return p.returncode or 0
    except Exception as e:
        logger.warning(f"pm2 {action} error: {e}")
        return 1


async def _pm2_vllm_running() -> bool:
    """Check if the ddn-vllm PM2 process is in online status."""
    try:
        p = await asyncio.create_subprocess_exec(
            PM2_BIN, "show", PM2_VLLM_NAME,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.DEVNULL,
        )
        stdout, _ = await p.communicate()
        return b"online" in stdout
    except Exception:
        return False


async def start_vllm() -> dict:
    global _vllm_status, _vllm_log_lines
    if _vllm_status in ("starting", "running"):
        return {"status": _vllm_status, "message": "vLLM is already starting/running"}

    _vllm_log_lines = ["⏳ Checking if vLLM already reachable…"]

    if await _is_healthy():
        _vllm_status = "running"
        return {"status": "running", "message": "vLLM was already reachable on :11000"}

    _vllm_status = "starting"

    # Step 1: Stop any stale ddn-vllm PM2 process from a previous session
    _vllm_log_lines.append("🧹 Removing stale ddn-vllm from PM2 (if any)…")
    await _pm2("delete", PM2_VLLM_NAME)

    # Step 2: Kill any lingering vLLM processes holding VRAM
    _vllm_log_lines.append("🧹 Killing lingering vLLM processes…")
    try:
        p = await asyncio.create_subprocess_shell(
            "pkill -9 -f 'vllm.entrypoints.openai' 2>/dev/null; "
            "pkill -9 -f 'EngineCore' 2>/dev/null; sleep 2; true",
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        await p.wait()
    except Exception:
        pass

    # Step 3: Pause GPU-competing services
    _vllm_log_lines.append(f"⏸ Stopping {', '.join(GPU_COMPETING_SERVICES)} to free VRAM…")
    for svc in GPU_COMPETING_SERVICES:
        await _pm2("stop", svc)
    await asyncio.sleep(8)   # Allow full VRAM release
    _vllm_log_lines.append("✅ VRAM freed — writing launch script…")

    # Step 4: Write the launch script
    _write_launch_script()

    # Step 5: Register and start via PM2
    _vllm_log_lines.append(f"🚀 Starting via PM2 as '{PM2_VLLM_NAME}'…")
    rc = await _pm2(
        "start", LAUNCH_SCRIPT,
        "--name", PM2_VLLM_NAME,
        "--no-autorestart",   # Don't auto-restart on crash during demo
        "--interpreter", "bash",
    )
    if rc != 0:
        _vllm_status = "error"
        _vllm_log_lines.append(f"❌ pm2 start failed (exit {rc})")
        await _pm2("start", *GPU_COMPETING_SERVICES)
        return {"status": "error", "message": f"pm2 start failed (exit {rc})"}

    _vllm_log_lines.append(f"✅ PM2 process '{PM2_VLLM_NAME}' started — health polling…")
    asyncio.create_task(_watch_startup())
    asyncio.create_task(_tail_pm2_logs())

    return {
        "status": "starting",
        "message": f"vLLM starting via PM2 as '{PM2_VLLM_NAME}' (~90s)",
    }


async def stop_vllm() -> dict:
    global _vllm_status
    _vllm_status = "stopping"

    await _pm2("stop", PM2_VLLM_NAME)
    await _pm2("delete", PM2_VLLM_NAME)

    # Kill any stray processes
    try:
        p = await asyncio.create_subprocess_shell(
            "pkill -9 -f 'vllm.entrypoints.openai' 2>/dev/null; "
            "pkill -9 -f 'EngineCore' 2>/dev/null; sleep 2; true",
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        await p.wait()
    except Exception:
        pass

    await asyncio.sleep(3)

    # Restore GPU-competing services
    for svc in GPU_COMPETING_SERVICES:
        await _pm2("start", svc)

    _vllm_status = "stopped"
    logger.info("vLLM stopped. GPU freed. RAG + VSS restored.")
    return {"status": "stopped", "message": "vLLM stopped — GPU freed. RAG & VSS restored."}


def get_status() -> dict:
    return {
        "status": _vllm_status,
        "port": VLLM_PORT,
        "model": "meta-llama/Llama-3.1-8B-Instruct",
        "recent_logs": _vllm_log_lines[-50:],
    }


# ── Internal helpers ───────────────────────────────────────────────────────────

async def _is_healthy() -> bool:
    def _check():
        try:
            with urllib.request.urlopen(VLLM_HEALTH_URL, timeout=2) as r:
                return r.status == 200
        except Exception:
            return False
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _check)


async def _watch_startup():
    """Poll /health until vLLM is ready or times out (150s)."""
    global _vllm_status
    for i in range(150):
        await asyncio.sleep(1)
        # Check if PM2 process is still alive
        if i % 10 == 0 and i > 0:
            alive = await _pm2_vllm_running()
            if not alive:
                _vllm_status = "error"
                _vllm_log_lines.append("❌ PM2 process exited — check pm2 logs ddn-vllm")
                logger.error("vLLM PM2 process died during startup")
                return
        if await _is_healthy():
            _vllm_status = "running"
            _vllm_log_lines.append(f"✅ vLLM READY on :{VLLM_PORT} after {i+1}s")
            logger.info(f"vLLM ready on :{VLLM_PORT} in {i+1}s")
            return
    _vllm_status = "error"
    _vllm_log_lines.append("❌ Timeout (150s) — run: pm2 logs ddn-vllm")
    logger.error("vLLM startup timed out after 150s")


async def _tail_pm2_logs():
    """Read PM2 stdout log for ddn-vllm and feed into _vllm_log_lines."""
    global _vllm_log_lines
    # PM2 stores logs in ~/.pm2/logs/ddn-vllm-out.log
    log_path = os.path.expanduser("~/.pm2/logs/ddn-vllm-out.log")
    err_path = os.path.expanduser("~/.pm2/logs/ddn-vllm-error.log")

    # Wait for log file to appear
    for _ in range(30):
        await asyncio.sleep(1)
        if os.path.exists(log_path) or os.path.exists(err_path):
            break

    async def tail_file(path):
        try:
            with open(path, "r") as f:
                f.seek(0, 2)  # Start from current end
                while _vllm_status == "starting":
                    line = f.readline()
                    if line:
                        line = line.rstrip()
                        _vllm_log_lines.append(line)
                        if len(_vllm_log_lines) > 300:
                            _vllm_log_lines = _vllm_log_lines[-300:]
                    else:
                        await asyncio.sleep(0.5)
        except Exception as e:
            logger.debug(f"tail_file({path}): {e}")

    tasks = []
    if os.path.exists(log_path):
        tasks.append(asyncio.create_task(tail_file(log_path)))
    if os.path.exists(err_path):
        tasks.append(asyncio.create_task(tail_file(err_path)))
    if tasks:
        await asyncio.gather(*tasks)
